package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/Lenstack/Lensaas/microservices/gateway/graphql/generated"
)

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, signin generated.SignInRequest) (*generated.SignIn, error) {
	panic(fmt.Errorf("not implemented: SignIn - signIn"))
}

// SignIn is the resolver for the signIn field.
func (r *queryResolver) SignIn(ctx context.Context, signin generated.SignInRequest) (*generated.SignIn, error) {
	panic(fmt.Errorf("not implemented: SignIn - signIn"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
