export {HomeHeader} from "./home.header"
export {HomeHero} from "./home.hero"
export {HomeFeature} from "./home.feature"
export {HomePricing} from "./home.pricing"
export {HomeFq} from "./home.fq"
export {HomeContact} from "./home.contact"
export {HomeFooter} from "./home.footer"

export {DashboardHeader} from "./dashboard.header"
export {DashboardAside} from "./dashboard.aside"
export {DashboardContent} from "./dashboard.content"