# Path: microservices\authentication\dockerfile
# Get Golang Version 1.19-alpine
FROM golang:1.19-alpine AS builder
# Set the Current Working Directory inside the container
WORKDIR /microservice
# Copy go mod and sum files
COPY go.mod go.sum ./
# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed
RUN go mod download
# Copy the source from the current directory to the Working Directory inside the container
COPY . ./
# Build the Go app
RUN go build -o authentication_microservice ./cmd/main.go
# This container exposes port 8080 to the outside world
EXPOSE 8080
# Command to run the executable
ENTRYPOINT ["/microservice/authentication_microservice"]







